<?php

namespace AppBundle\Entity\Repository;

/**
 * CalibrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalibrationRepository extends \Doctrine\ORM\EntityRepository
{


    public function gd()
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:Calibration c WHERE c.id < 5')
        ->getResult();

        return $query;

    }



}
