<?php

namespace AppBundle\Entity\Repository;

/**
 * CalibrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalibrationRepository extends \Doctrine\ORM\EntityRepository
{


    public function findById($id)
    {

    }



}
