<?php

namespace AppBundle\Entity\Repository;

/**
 * CalibrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{

        public function findAllEquipment()
        {
            return $this->findBy(array(), ['equipmentID' => 'ASC']);
        }




}
