<?php

namespace AppBundle\Entity\Repository;

/**
 * CalibrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{

        public function findAllEquipment()
        {
            return $this->findBy(array(), ['equipmentID' => 'ASC']);
        }

        public function findEquipmentJoinedWithTypes($id)
        {

            $query = $this->getEntityManager()
                ->createQuery('SELECT c from AppBundle:Classification c
                               JOIN c.equipment e
                               where e.id = :id')->setParameter('id', $id);

            return $query->getResult();


//
//            $query = $this->getEntityManager()
//                ->createQuery('SELECT i FROM AppBundle:Info i
//                            JOIN i.calibration c
//                            JOIN i.prefix p
//                            JOIN i.unit u
//                            WHERE c.id = :id')->setParameter('id', $id);
//
//            return $query->getResult();



        }




}
